myfirstprj/myfirstprj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),  #polls.urls 상대경로 (파이썬은 /,\ 대신 .을 사용)
    path('namespace/', include('namespace.urls')),
]

'''
myfirstprj -> polls
1차 url        2차 url

http://127.0.0.1:8000/polls        /main
                    (어플리케이션)    (기능)
'''

myfirstprj/polls/urls.py
from django.urls import path
from . import views

# app_name 변수는 주소에 라벨링을 합니다.
app_name = "polls"

urlpatterns = [
        path('main', views.index, name='index'),    # name: 별명 (main의 절대경로를 index라고 부르자!)
        path('test', views.test, name='test'),
        path('getform',views.getform, name='getform'),
        path('get', views.get, name='get'),
        path('nameform', views.nameform, name='nameform'),
        path('name',views.get_name, name='name'),
        path('<int:c>/ctof', views.ctof),
        path('<int:cm>/<int:kg>/bmi', views.BMI),
        path('<int:number>/content', views.get_number),  #가변(우아한) url. number: 가변, content: 고정
        path('<int:age>/check', views.get_adult_result),
        path('<int:num1>/<int:num2>/two', views.get_two),
        path('<str:name>/name', views.get_name2),   
        #실수(float)입력은 바로 안되기 때문에 문자열(str)로 받아서 형변환하기
        
        #<str:변수명>을 이용하면 문자열을 입력받을 수 있는데 문자열에는 반드시 문자만 들어가는게 아니라 .를  포함한 숫자도 넣을 수 있음
        #따라서 .를 포함한 숫자가 들어왔을 때 float()을 이용해 강제 형변환을 하면 실수 입력이 가능함.

        path('<str:won>/<str:rate>/exchange', views.exchange_won),
        path('qtest', views.qtest),
        path('<int:age>/bus', views.buscost),
        path('<int:id>', views.detail, name='detail'),
        path('<int:question_id>/results/', views.results, name='results'),
        path('<int:question_id>/vote/',views.vote, name='vote'),    #~~/polls/1/vote/?choice=2
    ]

myfirstprj/polls/models.py
from django.db import models

class Question(models.Model):   #Question : 테이블 이름
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):      #admin 페이지에서 노출되는 정보가 무엇이냐
        return str(self.pk) + ". " + self.question_text + " | " + str(self.pub_date)[:10]      
        #pub_date는 문자열이 아니기 때문에 형변환해야함
        #1. 당신이 좋아하는 음식은? | 2019-08-21 02:44:54    -> 1. 당신이 좋아하는 음식은? | 2019-08-21

class Choice(models.Model):     #Choice : 테이블 이름
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.question) + " | " + str(self.choice_text)

myfirstprj/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse    #브라우저상에 연결
from polls.models import Question
from django.template.context_processors import request
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse

#request는 요청을 받는 변수이기 때문에 무조건 써야함

def index(request):     #장고 쓸 때 함수 내부에 request 반드시 써야함
    latest_question_list = Question.objects.order_by('-pub_date')
    return render(request, 'polls/index.html',{"latest_question_list":latest_question_list})

def test(request):
    return render(request, 'polls/test.html')   #render: polls/templates/polls 안에 test.html를 연결해줌(현위치 templates)

def getform(request):
    return render(request, 'polls/getform.html')

def get(request):
    """
    #http://127.0.0.1:8000/polls/get?str1=가나다라&str2=abcd
    '''
    print(request.GET['str1'])  #가나다라 콘솔창에 출력됨
    return HttpResponse("<h1>"+ request.GET['str2'] + "</h1>")  #abcd 브라우저 창에 출력됨
    '''
    #str2에 값을 안넣으면 에러뜸. 즉 요청한걸 안넣으면 에러뜸
    
    #요청한 걸 안넣었을 때 에러 안뜨게 설정하기
    print(request.GET.get('str1'))
    return HttpResponse("<h1>"+ str(request.GET.get('str2')) + "</h1>")
    #http://127.0.0.1:8000/polls/get?str1=장고
    #str2에 안넣었지만 브라우저에는 None으로 나옴
    """
    str1 = request.POST.get('str1')
    str2 = request.POST.get('str2')
    return render(request, 'polls/get.html', {"str1":str1, "str2":str2})  #중요!!!!!!!

def nameform(request):    
    return render(request, 'polls/nameform.html')
    
def get_name(request):
    """
    name = str(request.GET.get('name'))
    return HttpResponse("<h1>사용자의 이름은: " + name + "입니다.</h1>")
    #http://127.0.0.1:8000/polls/name?name=python
    #사용자의 이름은: python입니다.
    """
    name = request.POST.get('name')
    return render(request, 'polls/get_name.html', {'name':name})
    
'''
get방식으로 섭씨 온도를 입력받아 화씨온도로 바꿔주는 프로그램
섭씨=(화씨-32)/1.8
'''
def ctof(request, c):
    '''
    c = int(request.GET.get('cel'))
    f = c * 1.8 + 32
    return HttpResponse("<h1>섭씨온도: " + str(c) + " 화씨온도: " + str(f) + "</h1>")
    #HttpResponse는 문자열에만 응답하기 때문에 모두 문자열로 바꿔줘야함
    #print는 자동으로 문자열로 바꿔줌. 문자열로 바꿀 필요없음
    
    f = c * 1.8 + 32
    return HttpResponse("<h1>섭씨온도: " + str(c) + " 화씨온도: " + str(f) + "</h1>")
    '''
    f = c * 1.8 + 32
    return render(request, 'polls/ctof.html', {"c":c,"f":f})
    
    
'''s
get방식으로 키, 몸무게를 입력받아 BMI지수를 출력하는 프로그램을 만들어보세요
BMI지수 공식: 몸무게(kg) / (키(m) * 키(m))
키는 cm단위로 입력받되 계산시는 m단위로 사용합니다
'''
def BMI(request, cm, kg):
    '''
    h = float(request.GET.get('height')) / 100
    w = float(request.GET.get('weight'))
    bmi = w / (h * h)
    return HttpResponse("<h1>bmi 지수는 " + str(round(bmi, 2)) + "입니다.</h1>")
    
    m = float(cm) / 100
    bmi = kg / (m * m)
    return HttpResponse("<h1>키 : " + str(cm) + "cm, 몸무게: " + str(kg) + "kg일 때  bmi 지수는 " 
                        +  str(round(bmi, 2)) + "입니다.</h1>")
    '''
    m = cm / 100.0
    bmi = kg / (m * m)
    bmi = round(bmi, 2)
    return render(request, 'polls/get_bmi.html', {'cm':cm, 'kg':kg, 'bmi':bmi})

def get_number(request, number):    
    return HttpResponse('<h1>테스트 중입니다.' + str(number) + "</h1>")

def get_adult_result(request, age):
    """
    person = ""
    if age >= 20:
        person = "성인입니다."
    else:
        person = "미성년자입니다."
    return HttpResponse("<h1>" + person + "</h1>")
    """
    """
    if age >= 20:
        return render(request, 'polls/adult_ok.html', {'age':age})
    else:
        return render(request, 'polls/adult_fail.html', {'age':age})
    """
    return render(request, 'polls/adult_check.html', {'age':age})

def get_two(request, num1, num2):
    return HttpResponse("<h1>" + str(num1) + " || " + str(num2) + "</h1>")

def get_name2(request, name):
    return HttpResponse("<h1>당신의 이름은: " + name + "입니다.</h1>")

def exchange_won(request, won, rate):
    dol = float(won) / float(rate)
    return HttpResponse("<h1>원화: " + won + "원, 환율: " +rate +
                        "달러일 때 환전금액: " + str(round(dol,2)) + "달러 입니다.</h1>")

def qtest(request):
    #question_all = Question.objects.all()   #저장된 순서로 모두 꺼내옴
    question_all = Question.objects.order_by('-pk')  #컬럼의 순서대로 정렬되어 꺼내옴
    return render(request, 'polls/question_test.html', {'question_all':question_all})

def buscost(request, age):
    return render(request, 'polls/bus_cost.html', {'age':age})

def detail(request, id):
    # .get(조건)은 결과가 무조건 1개만 나올 때 쓸 수 있습니다.
    #question = Question.objects.get(pk=id)
    question = get_object_or_404(Question, pk=id)
    return render(request, 'polls/detail.html', {'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results',args=(question_id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question':question})

myfirstprj/polls/templates/polls/adult_check.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>당신의 나이는 {{ age }}세 입니다</h1>
	{% if age >= 20 %}
		<h1>당신은 성인입니다. 주류나 담배를 구매할 수 있습니다.</h1>
	{% else %}
		<h1>당신은 미성년자입니다. 주류나 담배를 구매할 수 없습니다.</h1>
	{% endif %}
</body>
</html>

myfirstprj/polls/templates/polls/adult_fail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>나이가 {{age}}살인 당신은 미성년자입니다</h1>
</body>
</html>

myfirstprj/polls/templates/polls/adult_ok.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>나이가 {{age}}살인 당신은 성인입니다</h1>
</body>
</html>

myfirstprj/polls/templates/polls/bus_cost.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>당신의 나이는 {{age}}세 입니다.</h1>
	{% if age >= 65 %}
		<h1>노인 요금제입니다.</h1>
	{% elif age >= 20 %}
		<h1>성인 요금제입니다.</h1>
	{% elif age >= 8 %}
		<h1>청소년 요금제입니다.</h1>
	{% elif age >= 0 %}
		<h1>어린이 요금제입니다.</h1>
	{% endif %}
</body>
</html>

myfirstprj/polls/templates/polls/ctof.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>섭씨 -> 화씨 변환기</h1>
	<table border='1' width='300'>
		<tr>
			<th>섭씨</th><th>화씨</th>
		</tr>
		<tr>
			<td>{{ c }}도</td><td>{{ f }}도</td>
		</tr>
	</table>
</body>
</html>

myfirstprj/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{question.question_text}}</h1>
	<form action="{% url 'polls:vote' question.id %}" method='post'>
		{% csrf_token %}
		<!-- 현재 가져온 question과 연계된 choice의 항목 전체 -->
		{% for choice in question.choice_set.all %}
			<!-- forloop.counter는 1부터 한 바퀴마다 1씩 자동증가하는 변수 -->
			<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
			<label for="choice{{forloop.counter}}">		<!-- input의 id와 label의 for이 연결 -->
				{{choice.choice_text}}
			</label><br>
		{% endfor %}
		<input type="submit" value="투표하기">
	</form>
</body>
</html>

myfirstprj/polls/templates/polls/get.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>str1 파라미터의 값 : {{ str1 }}</h1>	
	<h1>str2 파라미터의 값 : {{ str2 }}</h1>
	<a href="{% url 'polls:index' %}">
		메인으로 돌아가기
	</a> <br>
</body>
</html>

myfirstprj/polls/templates/polls/get_bmi.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>bmi 측정기</h1>
	<table border='1' width='500'>
		<tr>
			<td>키</td><td>몸무게</td><td>BMI지수</td>
		</tr>
		<tr>
			<td>{{cm}}cm</td><td>{{kg}}kg</td><td>{{bmi}}</td>
		</tr>
	</table>
	<a href="{% url 'polls:index' %}">
		메인으로 돌아가기
	</a>
</body>
</html>

myfirstprj/polls/templates/polls/get_name.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>이름 입력받기</title>
</head>
<body>
	<h1>사용자의 이름은 : {{ name }} 입니다</h1>
	<a href="{% url 'polls:index' %}">
		메인으로 돌아가기
	</a><br>
</body>
</html>

myfirstprj/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	{% if latest_question_list %}	<!-- 자료가 있으면 true -->
		<ul>
			{% for question in latest_question_list %}
				<li>
					<!-- polls:detail 패턴은 가변숫자를 받기 때문에 가변숫자자리에 어떤 자료를 넣어줄지 결정해야함 -->
					<a href="{% url 'polls:detail' question.pk %}">		<!-- "/polls/{{question.pk}}" -->
						{{question.question_text}}
					</a>
				</li>
			{% endfor %}
		</ul>
	{% else %}	<!-- 자료가 없으면 false -->
		<p>No polls are available.</p>
	{% endif %}
</body>
</html>

myfirstprj/polls/templates/polls/nameform.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- form이란 특정 페이지에 보낼 양식을 작성하는 페이지입니다.
		form 태그를 이용해 작성하며 필수 작성 속성은
		action(목적지의 주소), method(get방식 post방식 선택)입니다. -->
	<!-- get방식은 주소에 전송정보를 담아서 보냅니다. -->
	<form action="{% url 'polls:name' %}" method="POST">
		{% csrf_token %}
		당신의 이름을 적어주세요:
		<!-- 일반적인 form은 어떤 이름에 자료를 담아서 보낼지 name 속성으로 지정합니다. -->
		<input type="text" name="name">
		<!-- submit은 제출버튼이며 value속성에 적은 값이 실제로 버튼에 새겨질 이름이 됩니다. -->
		<input type="submit" value="제출">
	</form>
</body>
</html>

myfirstprj/polls/templates/polls/question_test.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- 파이썬 구문을 장고 템플릿 내부에서 사용하고 싶다면 {(퍼센트기호) 구문 (퍼센트기호)}을 사용한다. -->
	{% for data in question_all %}
		<h1>{{data}}</h1>
	<!-- 파이썬 구문이지만 들여쓰기로 타겟 실행문 범위를 정하지 않으므로 끝나는 지점을 같이 작성해줘야함 -->
	{% endfor %}
</body>
</html>

myfirstprj/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{question.question_text}}</h1>
	<ul>
		{% for choice in question.choice_set.all %}
			<li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
		{% endfor %}
	</ul>
	<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

myfirstprj/polls/templates/polls/test.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>render함수 테스트</h1>
	<div>
		render 함수를 이용하면 이렇게<br>
		html파일을 완성시켜놓고 연결할 수 있습니다.
	</div>
	<div>
		이 파일은 HttpResponse 기준으로 한 문자열로 작성해야 하는<br>
		복잡한 코드를 보다 손쉽게 작성할 수 있게 만들어줍니다.
	</div>
	<a href="{% url 'polls:index' %}">		<!-- http://127.0.0.1:8000/polls/ 까지는 입력되어있음 -->
		main으로 돌아가기
	</a>
</body>
</html>