myfirstprj/myfirstprj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),  #polls.urls 상대경로 (파이썬은 /,\ 대신 .을 사용)
    path('namespace/', include('namespace.urls')),
]

'''
myfirstprj -> polls
1차 url        2차 url

http://127.0.0.1:8000/polls        /main
                    (어플리케이션)    (기능)
'''

myfirstprj/namespace/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from namespace import views

app_name = "namespace"

urlpatterns = [
    path('main', views.index, name='index'),
    path('lotto', views.lotto, name='lotto'),
    path('naver', views.naver, name='naver'),
    path('daum', views.daum, name='daum'),
    path('lotto_mv',views.lotto_mv, name="lotto_mv")
]

myfirstprj/polls/urls.py
from django.urls import path
from . import views

# app_name 변수는 주소에 라벨링을 합니다.
app_name = "polls"

urlpatterns = [
        path('main', views.index, name='index'),    # name: 별명 (main의 절대경로를 index라고 부르자!)
        path('test', views.test, name='test'),
        path('getform',views.getform, name='getform'),
        path('get', views.get, name='get'),
        path('nameform', views.nameform, name='nameform'),
        path('name',views.get_name, name='name'),
        path('<int:c>/ctof', views.ctof),
        path('<int:cm>/<int:kg>/bmi', views.BMI),
        path('<int:number>/content', views.get_number),  #가변(우아한) url. number: 가변, content: 고정
        path('<int:age>/check', views.get_adult_result),
        path('<int:num1>/<int:num2>/two', views.get_two),
        path('<str:name>/name', views.get_name2),   
        #실수(float)입력은 바로 안되기 때문에 문자열(str)로 받아서 형변환하기
        
        #<str:변수명>을 이용하면 문자열을 입력받을 수 있는데 문자열에는 반드시 문자만 들어가는게 아니라 .를  포함한 숫자도 넣을 수 있음
        #따라서 .를 포함한 숫자가 들어왔을 때 float()을 이용해 강제 형변환을 하면 실수 입력이 가능함.

        path('<str:won>/<str:rate>/exchange', views.exchange_won),
        path('qtest', views.qtest),
        path('<int:age>/bus', views.buscost),
        path('<int:id>', views.detail, name='detail'),
        path('<int:question_id>/results/', views.results, name='results'),
        path('<int:question_id>/vote/',views.vote, name='vote'),    #~~/polls/1/vote/?choice=2
    ]

myfirstprj/namespace/models.py
from django.db import models

# Create your models here.

myfirstprj/namespace/views.py
from django.shortcuts import render
import random
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse

def index(request):
    print(reverse('namespace:lotto'))   #namespace의 lotto 패턴 주소를 콘솔창에 찍은 것
    print(reverse('polls:test'))    #/polls/test
    print(reverse('polls:results', args=(10,)))     #우아한 url.    /polls/10/results/
    return render(request, 'namespace/index.html')

def lotto(request):
    lottonum = []
    while len(lottonum) != 6:
        number = random.randint(1,45)
        if number not in lottonum:
            lottonum.append(number)
    lottonum.sort()  
    while number in lottonum:
        number = random.randint(1,45)
    return render(request, 'namespace/lotto.html',{"lottonum":lottonum, "number":number})    

def naver(request):
    print("네이버 페이지로 강제 링크됩니다.")
    return HttpResponseRedirect('https://www.naver.com')

def lotto_mv(request):
    print("로또 사이트로 이동하셨습니다")
    return HttpResponseRedirect('/namespace/lotto')

def daum(request):
    print("다음 사이트로 이동하셨습니다")
    return HttpResponseRedirect('https://www.daum.net')

myfirstprj/namespace/templates/namespace/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>namespace 어플리케이션의 메인페이지입니다</h1>
	<a href="{% url 'namespace:lotto' %}">로또추첨 페이지로 이동</a><br>
	<a href="http://www.naver.com">네이버 페이지로 이동</a><br>
	<a href="{% url 'namespace:naver' %}">네이버 페이지로 이동(집계)</a><br>
	<a href="http://www.daum.net">다음 페이지로 이동</a><br>
	<a href="{% url 'namespace:daum' %}">다음페이지로 이동(집계)</a><br>
	<a href="{% url 'namespace:lotto_mv' %}">로또페이지로 이동(집계)</a>
</body>
</html>

myfirstprj/namespace/templates/namespace/lotto.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>로또복권 1등 당첨번호 : 
	{% for i in lottonum %}
		{{i}}
	{% endfor %} </h1>
	<h1> 보너스번호 : {{ number }}</h1> 
	<a href="{% url 'namespace:index' %}">메인으로</a><br>
	<a href="{% url 'namespace:lotto' %}">재추첨</a>
</body>
</html>